using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.PackageManager;
using UnityEngine;

namespace Aexxa.CanvasCore.Editor
{
    /// <summary>
    /// Writes a real [MenuItem] per prefab found in the configured folder (GameObject > Canvas Core >
    /// Create > {prefab name}, one click, exactly like Unity's own "GameObject > UI > Button") into a
    /// generated .cs file. Doesn't care what the prefab is — UI element, plain game object, anything.
    /// Deliberately NOT wired to an AssetPostprocessor that regenerates on every asset change — that would
    /// mean an unpredictable recompile every time any file moves. Instead this only runs when explicitly
    /// asked: the "Scan &amp; Generate Menu" button on the CanvasCoreSettings asset, the Tools menu below,
    /// or once automatically if the generated file is missing entirely (first checkout).
    ///
    /// Each generated item calls DesignSystemCreateMenu.CreateByName(prefabName, ...) rather than baking
    /// in an absolute asset path — a baked path only matches the checkout it was generated from, and
    /// breaks for every consumer whose install location differs (e.g. a git-URL package resolves under
    /// Packages/com.aexxa.canvascore/ instead of Assets/Plugins/aexxa/CanvasCore/). Resolving by name
    /// against the live folder at click time keeps the shipped, pre-generated menu working regardless of
    /// where the package physically ends up.
    /// </summary>
    internal static class DesignSystemMenuGenerator
    {
        private static string GeneratedFilePath
        {
            get
            {
                var packageInfo = PackageInfo.FindForAssembly(typeof(DesignSystemMenuGenerator).Assembly);
                var packageRoot = packageInfo != null ? packageInfo.assetPath : "Assets/Plugins/aexxa/CanvasCore";
                return $"{packageRoot}/Editor/DesignSystem/Generated/DesignSystemCreateMenuItems.generated.cs";
            }
        }

        /// <summary>
        /// Git/registry/tarball package installs are mounted read-only — writing the generated file back
        /// into them fails (or silently lands nowhere useful). Only a local/embedded package checkout, or a
        /// plain vendored copy sitting under Assets/ (no PackageInfo at all), can be regenerated in place.
        /// </summary>
        private static bool IsPackageWritable
        {
            get
            {
                var packageInfo = PackageInfo.FindForAssembly(typeof(DesignSystemMenuGenerator).Assembly);
                return packageInfo == null
                    || packageInfo.source == PackageSource.Local
                    || packageInfo.source == PackageSource.Embedded;
            }
        }

        [InitializeOnLoadMethod]
        private static void GenerateOnceIfMissing()
        {
            if (!IsPackageWritable)
            {
                return;
            }

            if (!File.Exists(ToAbsolutePath(GeneratedFilePath)))
            {
                ScanAndGenerate();
            }
        }

        [MenuItem("Tools/CanvasCore/Scan Create Menu Prefabs")]
        internal static void ScanAndGenerate()
        {
            if (!IsPackageWritable)
            {
                Debug.LogWarning(
                    "CanvasCore: this package copy is read-only (installed via git URL / registry), so the " +
                    "Create menu can't be regenerated here. It ships pre-generated and resolves prefabs by " +
                    "name at runtime, so no action is needed unless you're developing the package itself.");
                return;
            }

            var baseFolder = DesignSystemCreateMenu.ConfiguredBaseFolder;
            var candidates = DesignSystemCreateMenu.FindPrefabsInFolder(baseFolder);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Tools > CanvasCore > Scan Create Menu Prefabs (or the \"Scan & Generate Menu\"");
            sb.AppendLine("// button on the CanvasCoreSettings asset). Do not edit by hand — re-running the scan overwrites it.");
            sb.AppendLine($"// Scanned folder: {baseFolder}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Aexxa.CanvasCore.Editor");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class DesignSystemCreateMenuItems");
            sb.AppendLine("    {");

            // Low priority so "Canvas Core" sorts near the top of the GameObject menu, close to
            // "Create Empty" (priority 0), instead of past Volume/Camera near the bottom.
            var priority = 0;
            foreach (var (_, prefab) in candidates)
            {
                var label = prefab.name;
                var methodName = "Create_" + SanitizeIdentifier(prefab.name);

                sb.AppendLine($"        [MenuItem(\"GameObject/Canvas Core/Create/{EscapeForMenuPath(label)}\", false, {priority})]");
                sb.AppendLine($"        private static void {methodName}(MenuCommand menuCommand) =>");
                sb.AppendLine($"            DesignSystemCreateMenu.CreateByName(\"{EscapeForString(label)}\", menuCommand.context as GameObject);");
                sb.AppendLine();

                priority++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var absolutePath = ToAbsolutePath(GeneratedFilePath);
            Directory.CreateDirectory(Path.GetDirectoryName(absolutePath));
            File.WriteAllText(absolutePath, sb.ToString());

            AssetDatabase.ImportAsset(GeneratedFilePath, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh();

            Debug.Log($"CanvasCore Create Menu: generated {candidates.Count} menu item(s) from '{baseFolder}'.");
        }

        private static string ToAbsolutePath(string assetsRelativePath)
        {
            var projectRoot = Directory.GetParent(Application.dataPath).FullName;
            return Path.Combine(projectRoot, assetsRelativePath);
        }

        private static string SanitizeIdentifier(string name)
        {
            var sb = new StringBuilder(name.Length);
            foreach (var c in name)
            {
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            }
            return sb.ToString();
        }

        private static string EscapeForMenuPath(string label) => label.Replace("\"", "'");

        private static string EscapeForString(string label) => label.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
