using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Aexxa.CanvasCore.Editor
{
    /// <summary>
    /// Writes a real [MenuItem] per prefab found in the configured folder (GameObject > Canvas Core >
    /// Create > {prefab name}, one click, exactly like Unity's own "GameObject > UI > Button") into a
    /// generated .cs file. Doesn't care what the prefab is — UI element, plain game object, anything.
    /// Deliberately NOT wired to an AssetPostprocessor that regenerates on every asset change — that would
    /// mean an unpredictable recompile every time any file moves. Instead this only runs when explicitly
    /// asked: the "Scan &amp; Generate Menu" button on the CanvasCoreSettings asset, the Tools menu below,
    /// or once automatically if the generated file is missing entirely and there is a folder to scan (first
    /// checkout). Importing does not trigger it: writing a script forces a domain reload, which is not
    /// something an import should spring on you.
    ///
    /// The generated file always lives under Assets/ (see GeneratedFilePath) — it is never shipped inside
    /// the package itself, so there is exactly one copy, owned by the project. Each generated item calls
    /// DesignSystemCreateMenu.CreateByName(prefabName, ...) rather than baking in a full asset path, so
    /// moving/renaming a prefab within the scanned folder doesn't require
    /// regenerating — only adding or removing a prefab does.
    /// </summary>
    internal static class DesignSystemMenuGenerator
    {
        /// <summary>Base priority of every generated GameObject menu item. See ScanAndGenerate for why it is negative.</summary>
        private const int MenuPriority = -1000;

        private const string GeneratedFilePath = "Assets/Plugins/aexxa/CanvasCore/Editor/DesignSystem/Generated/DesignSystemCreateMenuItems.generated.cs";

        /// <summary>
        /// The safety net for a fresh checkout, and nothing more — importing deliberately does not scan, since
        /// generating a script mid-import means an unannounced recompile.
        ///
        /// <para>The folder check is what keeps the net from firing at the wrong moment. Before Examples are
        /// imported the Design System folder does not exist, so a scan would write a file with no menu items in
        /// it — and because this only runs when the file is <i>missing</i>, that empty file would then be the
        /// last word: the Create menu would stay empty after importing, with nothing to suggest a scan was
        /// needed. Waiting until there is a folder to scan means the first reload after an import fills the
        /// menu, and until then the file's absence still says "not generated yet".</para>
        /// </summary>
        [InitializeOnLoadMethod]
        private static void GenerateOnceIfMissing()
        {
            if (File.Exists(ToAbsolutePath(GeneratedFilePath)))
            {
                return;
            }

            if (AssetDatabase.IsValidFolder(DesignSystemCreateMenu.ConfiguredBaseFolder))
            {
                ScanAndGenerate();
            }
        }

        [MenuItem("Tools/CanvasCore/Scan Create Menu Prefabs")]
        internal static void ScanAndGenerate()
        {
            var baseFolder = DesignSystemCreateMenu.ConfiguredBaseFolder;
            var candidates = DesignSystemCreateMenu.FindPrefabsInFolder(baseFolder);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Tools > CanvasCore > Scan Create Menu Prefabs (or the \"Scan & Generate Menu\"");
            sb.AppendLine("// button on the CanvasCoreSettings asset). Do not edit by hand — re-running the scan overwrites it.");
            sb.AppendLine($"// Scanned folder: {baseFolder}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Aexxa.CanvasCore.Editor");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class DesignSystemCreateMenuItems");
            sb.AppendLine("    {");

            // Negative, so "Canvas Core" sits at the very top of the GameObject menu. Unity's own entries
            // start at 0 ("Create Empty") and climb from there, and an unprioritised menu item defaults to
            // 1000 and lands at the bottom - a submenu is placed by the lowest priority among its items, so
            // anything below zero puts this group first. The gap to 0 is far wider than the 11 Unity needs to
            // draw a separator, which is what keeps it visually its own block rather than crowding
            // "Create Empty".
            var priority = MenuPriority;
            foreach (var (_, prefab) in candidates)
            {
                var label = prefab.name;
                var methodName = "Create_" + SanitizeIdentifier(prefab.name);

                sb.AppendLine($"        [MenuItem(\"GameObject/Canvas Core/Create/{EscapeForMenuPath(label)}\", false, {priority})]");
                sb.AppendLine($"        private static void {methodName}(MenuCommand menuCommand) =>");
                sb.AppendLine($"            DesignSystemCreateMenu.CreateByName(\"{EscapeForString(label)}\", menuCommand.context as GameObject);");
                sb.AppendLine();

                priority++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var absolutePath = ToAbsolutePath(GeneratedFilePath);
            Directory.CreateDirectory(Path.GetDirectoryName(absolutePath));
            File.WriteAllText(absolutePath, sb.ToString());

            AssetDatabase.ImportAsset(GeneratedFilePath, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh();

            Debug.Log($"CanvasCore Create Menu: generated {candidates.Count} menu item(s) from '{baseFolder}'.");
        }

        private static string ToAbsolutePath(string assetsRelativePath) =>
            Path.Combine(Application.dataPath, assetsRelativePath["Assets/".Length..]);

        private static string SanitizeIdentifier(string name)
        {
            var sb = new StringBuilder(name.Length);
            foreach (var c in name)
            {
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            }
            return sb.ToString();
        }

        private static string EscapeForMenuPath(string label) => label.Replace("\"", "'");

        private static string EscapeForString(string label) => label.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
