using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Aexxa.CanvasCore.Editor
{
    /// <summary>
    /// Writes a real [MenuItem] per prefab found in the configured folder (GameObject > Canvas Core >
    /// Create > {prefab name}, one click, exactly like Unity's own "GameObject > UI > Button") into a
    /// generated .cs file. Doesn't care what the prefab is — UI element, plain game object, anything.
    /// Deliberately NOT wired to an AssetPostprocessor that regenerates on every asset change — that would
    /// mean an unpredictable recompile every time any file moves. Instead this only runs when explicitly
    /// asked: the "Scan &amp; Generate Menu" button on the CanvasCoreSettings asset (mirrors UICatalogSO's
    /// "Scan Resources/UI" button — scan is a deliberate action, not a background watcher), the
    /// Tools menu below, or once automatically if the generated file is missing entirely (first checkout).
    /// </summary>
    internal static class DesignSystemMenuGenerator
    {
        private const string GeneratedFilePath = "Assets/Plugins/aexxa/CanvasCore/Editor/DesignSystem/Generated/DesignSystemCreateMenuItems.generated.cs";

        [InitializeOnLoadMethod]
        private static void GenerateOnceIfMissing()
        {
            if (!File.Exists(ToAbsolutePath(GeneratedFilePath)))
            {
                ScanAndGenerate();
            }
        }

        [MenuItem("Tools/CanvasCore/Scan Create Menu Prefabs")]
        internal static void ScanAndGenerate()
        {
            var baseFolder = DesignSystemCreateMenu.ConfiguredBaseFolder;
            var candidates = DesignSystemCreateMenu.FindPrefabsInFolder(baseFolder);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Tools > CanvasCore > Scan Create Menu Prefabs (or the \"Scan & Generate Menu\"");
            sb.AppendLine("// button on the CanvasCoreSettings asset). Do not edit by hand — re-running the scan overwrites it.");
            sb.AppendLine($"// Scanned folder: {baseFolder}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Aexxa.CanvasCore.Editor");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class DesignSystemCreateMenuItems");
            sb.AppendLine("    {");

            // Low priority so "Canvas Core" sorts near the top of the GameObject menu, close to
            // "Create Empty" (priority 0), instead of past Volume/Camera near the bottom.
            var priority = 0;
            foreach (var (path, prefab) in candidates)
            {
                var label = prefab.name;
                var methodName = "Create_" + SanitizeIdentifier(prefab.name);

                sb.AppendLine($"        [MenuItem(\"GameObject/Canvas Core/Create/{EscapeForMenuPath(label)}\", false, {priority})]");
                sb.AppendLine($"        private static void {methodName}(MenuCommand menuCommand) =>");
                sb.AppendLine($"            DesignSystemCreateMenu.CreateFromBase(\"{path}\", menuCommand.context as GameObject);");
                sb.AppendLine();

                priority++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var absolutePath = ToAbsolutePath(GeneratedFilePath);
            Directory.CreateDirectory(Path.GetDirectoryName(absolutePath));
            File.WriteAllText(absolutePath, sb.ToString());

            AssetDatabase.ImportAsset(GeneratedFilePath, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh();

            Debug.Log($"CanvasCore Create Menu: generated {candidates.Count} menu item(s) from '{baseFolder}'.");
        }

        private static string ToAbsolutePath(string assetsRelativePath) =>
            Path.Combine(Application.dataPath, assetsRelativePath["Assets/".Length..]);

        private static string SanitizeIdentifier(string name)
        {
            var sb = new StringBuilder(name.Length);
            foreach (var c in name)
            {
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            }
            return sb.ToString();
        }

        private static string EscapeForMenuPath(string label) => label.Replace("\"", "'");
    }
}
